config/routes.rb
Rails.application.routes.draw do
  root 'tweets#index'
  post '/tweets/', to: 'tweets#create'
  delete '/tweet/:id(.:format)', to: 'tweets#delete', as: 'tweet'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  validates :content, presence: true, length: { maximum: 140 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @tweets = Tweet.all.reverse
  end

  def create
    @tweet = Tweet.new(tweets_params)
    @tweet.save
    redirect_to root_path
  end

  def delete
    @tweet = Tweet.find(params[:id])
    @tweet.destroy
    redirect_to root_path
  end

  private
  def tweets_params
    params.require(:tweets).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlitwitterFinal</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tweets/index.html.erb
<h1>Ali Twitter V1</h1>
<%= form_with scope: :tweets, url: tweets_path, local: true do |form| %>
  <p> <%= form.text_area :content, maxlength: 139, size: "50x5", :value => "What's Happening?" %> </p>
  <p> <%= form.submit "Tweets!" %> </p>
<% end %>
<h2>Tweets</h2>
<table>
  <% @tweets.each do |tweet| %>
  <tr>
    <table id="<%= dom_id(tweet) %>">
      <tr>
        <td> <p style="white-space: pre-line;"> <%= tweet.content %> </p> </td>
      </tr>
      <tr>
        <td> <%= tweet.created_at %> </td>
        <td> <%= link_to 'delete', tweet_path(tweet), method: 'delete' %> </td>
      </tr>
    </table>
  </tr>
  &nbsp;
  <% end %>
</table>